"""empty message

Revision ID: 17697e98726
Revises: 54cdbb8b98d6
Create Date: 2015-11-24 17:42:59.108834

"""

# revision identifiers, used by Alembic.
revision = '17697e98726'
down_revision = '54cdbb8b98d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_groups',
    sa.Column('auth_user_id', sa.Integer(), nullable=True),
    sa.Column('contact_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['contact_group_id'], ['contact_group.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_groups')
    op.drop_table('contact_group')
    ### end Alembic commands ###
