"""empty message

Revision ID: 2900e8c794e5
Revises: c84b3276ce9
Create Date: 2015-11-27 12:00:40.663843

"""

# revision identifiers, used by Alembic.
revision = '2900e8c794e5'
down_revision = 'c84b3276ce9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'plan_last_change')
    op.drop_column('plan', 'plan_expires')
    op.drop_column('plan', 'plan_bought')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('plan_bought', mysql.DATETIME(), nullable=True))
    op.add_column('plan', sa.Column('plan_expires', mysql.DATETIME(), nullable=True))
    op.add_column('plan', sa.Column('plan_last_change', mysql.DATETIME(), nullable=True))
    ### end Alembic commands ###
