"""empty message

Revision ID: 34845ae07f9c
Revises: 53943ac9bd07
Create Date: 2015-11-23 16:14:59.307524

"""

# revision identifiers, used by Alembic.
revision = '34845ae07f9c'
down_revision = '53943ac9bd07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('read', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    ### end Alembic commands ###
