"""empty message

Revision ID: 3b84fffd08dd
Revises: 3076a22ec140
Create Date: 2015-12-01 11:01:56.122976

"""

# revision identifiers, used by Alembic.
revision = '3b84fffd08dd'
down_revision = '3076a22ec140'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('expire', sa.Boolean(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['user'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset_token')
    ### end Alembic commands ###
