"""empty message

Revision ID: 54cdbb8b98d6
Revises: 34845ae07f9c
Create Date: 2015-11-24 16:58:50.282043

"""

# revision identifiers, used by Alembic.
revision = '54cdbb8b98d6'
down_revision = '34845ae07f9c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'auth_user', sa.Column('permission_type', mysql.ENUM('a', 'v', 'c'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'auth_user', 'permission_type')
    ### end Alembic commands ###
