"""empty message

Revision ID: 58e02675d725
Revises: 17697e98726
Create Date: 2015-11-25 10:29:03.665457

"""

# revision identifiers, used by Alembic.
revision = '58e02675d725'
down_revision = '17697e98726'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_group', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contact_group', 'auth_user', ['owner'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact_group', type_='foreignkey')
    op.drop_column('contact_group', 'owner')
    ### end Alembic commands ###
