"""empty message

Revision ID: c84b3276ce9
Revises: 58e02675d725
Create Date: 2015-11-26 11:17:45.925140

"""

# revision identifiers, used by Alembic.
revision = 'c84b3276ce9'
down_revision = '58e02675d725'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'auth_user_ibfk_2', 'auth_user', type_='foreignkey')
    op.drop_column('auth_user', 'plan_details')
    op.add_column('plan', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plan', 'auth_user', ['user_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plan', type_='foreignkey')
    op.drop_column('plan', 'user_id')
    op.add_column('auth_user', sa.Column('plan_details', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'auth_user_ibfk_2', 'auth_user', 'plan', ['plan_details'], ['id'])
    ### end Alembic commands ###
